version: "2"
services:
        server:
                build:
                        context: server
                        dockerfile: Dockerfile
                ports:
                - "8000:8000"